
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '0CBF7C8C9C040C8875CD22B9093498BB'
    
_lr_action_items = {')':([5,6,7,9,11,],[-3,-4,9,-2,-5,]),'(':([0,1,2,5,6,7,9,10,11,],[2,2,2,-3,2,2,-2,2,2,]),'BACKSLASH':([0,1,2,5,6,7,9,10,11,],[3,3,3,-3,3,3,-2,3,3,]),'.':([8,],[10,]),'VARIABLE':([0,1,2,3,5,6,7,9,10,11,],[5,5,5,8,-3,5,5,-2,5,5,]),'$end':([1,4,5,6,9,11,],[-1,0,-3,-4,-2,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Term':([0,1,2,6,7,10,11,],[1,6,7,6,6,11,6,]),'Program':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Program","S'",1,None,None,None),
  ('Program -> Term','Program',1,'p_start','parser.py',32),
  ('Term -> ( Term )','Term',3,'p_paren','parser.py',37),
  ('Term -> VARIABLE','Term',1,'p_variable','parser.py',44),
  ('Term -> Term Term','Term',2,'p_application','parser.py',49),
  ('Term -> BACKSLASH VARIABLE . Term','Term',4,'p_abstraction','parser.py',54),
]
